package de.unikassel.vs.alica.planDesigner.events;

public enum ModelEventType {
    ELEMENT_FOLDER_DELETED, ELEMENT_CREATED,  ELEMENT_ATTRIBUTE_CHANGED, ELEMENT_DELETED, ELEMENT_PARSED, ELEMENT_SERIALIZED, ELEMENT_ADDED, ELEMENT_REMOVED, ELEMENT_CONNECTED, ELEMENT_DISCONNECTED, ELEMENT_CHANGED_POSITION;
}
