package de.unikassel.vs.alica.planDesigner.events;

public enum ModelQueryType {
    DELETE_ELEMENT, CREATE_ELEMENT, PARSE_ELEMENT, ADD_ELEMENT, REMOVE_ELEMENT, REMOVE_ALL_ELEMENTS, SAVE_ELEMENT, RELOAD_ELEMENT, CHANGE_ELEMENT, MOVE_ELEMENT ,GENERATE_ELEMENT, GENERATE_ALL_EMEMENTS
}