package de.unikassel.vs.alica.planDesigner.alicamodel;

import javafx.beans.InvalidationListener;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleDoubleProperty;
import javafx.beans.property.SimpleObjectProperty;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class Plan extends AbstractPlan {

    protected final SimpleBooleanProperty masterPlan = new SimpleBooleanProperty();
    protected final SimpleDoubleProperty utilityThreshold = new SimpleDoubleProperty();
    protected final ObjectProperty<PreCondition> preCondition = new SimpleObjectProperty<>();
    protected final ObjectProperty<RuntimeCondition> runtimeCondition = new SimpleObjectProperty<>();

    protected final ArrayList<EntryPoint> entryPoints = new ArrayList<>();
    protected final ArrayList<State> states = new ArrayList<>();
    protected final ArrayList<Transition> transitions = new ArrayList<>();
    protected final ArrayList<Synchronisation> synchronisations = new ArrayList<>();

    /**
     * Need to be explicitly written, because the constructor Plan(long id)
     * makes the autogenerated version of this one vanishing.
     */
    public Plan() {
        super();
    }

    /**
     * Constructor for representing incomplete Plan References while parsing files.
     * @param id The ID found in the file, while parsing the reference.
     */
    public Plan(long id) {
        this();
        this.id = id ;
    }

    public double getUtilityThreshold() {
        return utilityThreshold.get();
    }
    public void setUtilityThreshold(double utilityThreshold) {
        this.utilityThreshold.set(utilityThreshold);
    }
    public SimpleDoubleProperty utilityThreshold() {
        return utilityThreshold;
    }

    public boolean getMasterPlan() {
        return masterPlan.get();
    }
    public void setMasterPlan(boolean masterPlan) {
        this.masterPlan.set(masterPlan);
    }
    public SimpleBooleanProperty masterPlanProperty() {
        return masterPlan;
    }

    public PreCondition getPreCondition() {
        return preCondition.get();
    }
    public void setPreCondition(PreCondition preCondition) {
        this.preCondition.set(preCondition);
        if(preCondition != null) {
            preCondition.registerDirtyFlagToAbstractPlan(this);
        }
    }
    public ObjectProperty<PreCondition> preConditionProperty(){
        return preCondition;
    }

    public RuntimeCondition getRuntimeCondition() {
        return runtimeCondition.get();
    }
    public void setRuntimeCondition(RuntimeCondition runtimeCondition) {
        this.runtimeCondition.set(runtimeCondition);
        if(runtimeCondition != null) {
            runtimeCondition.registerDirtyFlagToAbstractPlan(this);
        }
    }
    public ObjectProperty<RuntimeCondition> runtimeConditionProperty(){
        return runtimeCondition;
    }

    public void addTransition(Transition transition) {
        transitions.add(transition);
        this.setDirty(true);
    }
    public void removeTransition(Transition transition) {
        transitions.remove(transition);
        this.setDirty(true);
    }
    public List<Transition> getTransitions() {
        return Collections.unmodifiableList(transitions);
    }

    public void addState(State state) {
        states.add(state);
        this.setDirty(true);
    }
    public void removeState(State state) {
        states.remove(state);
        this.setDirty(true);
    }
    public List<State> getStates() {
        return Collections.unmodifiableList(states);
    }

    public void addSynchronisation(Synchronisation synchronisation) {
        synchronisations.add(synchronisation);
        synchronisation.dirtyProperty().addListener((observable, oldValue, newValue) -> {
            this.setDirty(true);
        });
        this.setDirty(true);
    }
    public void removeSynchronisation(Synchronisation synchronisation) {
        synchronisations.remove(synchronisation);
        this.setDirty(true);
    }
    public List<Synchronisation> getSynchronisations() {
        return Collections.unmodifiableList(synchronisations);
    }

    public void addEntryPoint(EntryPoint entryPoint) {
        entryPoints.add(entryPoint);
        this.setDirty(true);
    }
    public void removeEntryPoint(EntryPoint entryPoint) {
        entryPoints.remove(entryPoint);
        this.setDirty(true);
    }
    public List<EntryPoint> getEntryPoints() {
        return Collections.unmodifiableList(entryPoints);
    }

    @Override
    public void registerDirtyFlag() {
        super.registerDirtyFlag();
        InvalidationListener dirty = obs -> this.setDirty(true);
        masterPlan.addListener(dirty);
        utilityThreshold.addListener(dirty);
        preCondition.addListener(dirty);
        runtimeCondition.addListener(dirty);

        for (Synchronisation synchronisation : synchronisations) {
            synchronisation.dirtyProperty().addListener(dirty);
        }

        for (Variable variable : variables) {
            variable.nameProperty().addListener(dirty);
            variable.commentProperty().addListener(dirty);
            variable.variableTypeProperty().addListener(dirty);
        }

        this.setDirty(false);
    }

    @Override
    public void removeVariable(Variable variable) {
        super.removeVariable(variable);

        // Remove the Variable from all child-elements
        if(getPreCondition() != null) {
            getPreCondition().removeVariable(variable);
        }
        if(getRuntimeCondition() != null) {
            getRuntimeCondition().removeVariable(variable);
        }
        for(State state : getStates()) {
            if(state instanceof TerminalState && ((TerminalState) state).getPostCondition() != null) {
                ((TerminalState) state).getPostCondition().removeVariable(variable);
            }
        }
        for(Transition transition : getTransitions()) {
            if(transition.getPreCondition() != null) {
                transition.getPreCondition().removeVariable(variable);
            }
        }
    }
}
