package de.uni_kassel.vs.cn.planDesigner.events;

public enum GuiEventType {
    CREATE_ELEMENT, DELETE_ELEMENT, ADD_ELEMENT, REMOVE_ELEMENT, REMOVE_ALL_ELEMENTS, SHOW_USAGE, SAVE_ELEMENT, RELOAD_ELEMENT, CHANGE_ELEMENT, MOVE_ELEMENT
}
