package de.uni_kassel.vs.cn.planDesigner.events;

public enum ModelQueryType {
    DELETE_ELEMENT, CREATE_ELEMENT, PARSE_ELEMENT, ADD_ELEMENT, REMOVE_ELEMENT, REMOVE_ALL_ELEMENTS, SAVE_ELEMENT, RELOAD_ELEMENT, CHANGE_ELEMENT
}