package configuration;

import java.io.File;
import java.nio.file.Path;

/**
 * Created by marci on 16.10.16.
 */

public class Configuration {

    private Path rolesPath;

    private Path rootPath;

    private Path plansPath;

    /**
     * Path to generated code
     */
    private Path expressionValidatorsPath;

    private Path miscPath;

    public Configuration() {
        try {
            setPlansPath(new File("/home/marci/cnws/src/cnc-msl/etc/plans").toPath());
            setExpressionValidatorsPath(new File("/home/marci/cnws/src/cnc-msl/msl_expressions/autogenerated").toPath());
            setMiscPath(new File("/home/marci/cnws/src/cnc-msl/etc/Misc").toPath());
            setRolesPath(new File("/home/marci/cnws/src/cnc-msl/etc/roles").toPath());

        } catch (RuntimeException e) {
            e.printStackTrace();
        }
    }

    public Path getRolesPath() {
        return rolesPath;
    }

    public void setRolesPath(Path rolesPath) {
        this.rolesPath = rolesPath;
    }

    public Path getRootPath() {
        return rootPath;
    }

    public void setRootPath(Path rootPath) {
        this.rootPath = rootPath;
    }

    public Path getPlansPath() {
        return plansPath;
    }

    public void setPlansPath(Path plansPath) {
        this.plansPath = plansPath;
    }

    public Path getExpressionValidatorsPath() {
        return expressionValidatorsPath;
    }

    public void setExpressionValidatorsPath(Path expressionValidatorsPath) {
        this.expressionValidatorsPath = expressionValidatorsPath;
    }

    public Path getMiscPath() {
        return miscPath;
    }

    public void setMiscPath(Path miscPath) {
        this.miscPath = miscPath;
    }
}
