package de.unikassel.vs.alica.planDesigner.command.delete;

import de.unikassel.vs.alica.planDesigner.alicamodel.Behaviour;
import de.unikassel.vs.alica.planDesigner.command.Command;
import de.unikassel.vs.alica.planDesigner.events.ModelEventType;
import de.unikassel.vs.alica.planDesigner.modelmanagement.ModelManager;
import de.unikassel.vs.alica.planDesigner.modelmanagement.ModelModificationQuery;
import de.unikassel.vs.alica.planDesigner.modelmanagement.Types;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Paths;

public class DeleteBehaviour extends Command {

    protected Behaviour behaviour;
    private String textH;
    private String textCPP;
    private File pathH;
    private File pathCPP;

    public DeleteBehaviour(ModelManager modelManager, ModelModificationQuery mmq) {
        super(modelManager, mmq);
        behaviour = (Behaviour) modelManager.getPlanElement(mmq.getElementId());
    }

    @Override
    public void doCommand() {
        if (behaviour == null) {
            return;
        }

        //Get the generated Files
        String path = modelManager.getGeneratedFilesForBehaviour(behaviour);
        path = path.replace("[","");
        path = path.replace("]","");
        String[] split = path.split(", ");
        pathH = new File(split[0]);
        pathCPP = new File(split[1]);
        if(pathH.exists() && pathCPP.exists()) {
            try {
                textH = new String (Files.readAllBytes(Paths.get(pathH.toString())));
                textCPP = new String (Files.readAllBytes(Paths.get(pathCPP.toString())));
            } catch (Exception e) {
                e.getMessage();
            }
            pathH.delete();
            pathCPP.delete();
        } else {
            System.out.println("ERROR:" + behaviour.getName() + ".h and " + behaviour.getName() + ".cpp are not autogenerated!!!");
        }

        modelManager.dropPlanElement(Types.BEHAVIOUR, behaviour, true);
        this.fireEvent(ModelEventType.ELEMENT_DELETED, this.behaviour);
    }

    @Override
    public void undoCommand() {
        if (behaviour == null) {
            return;
        }
        //Write back the autogenerated files, if available
        try {
            if(!textH.isEmpty()) {
                PrintWriter writerH = new PrintWriter(new FileWriter(pathH, true));
                writerH.print(textH);
                writerH.close();
            }
            if(!textCPP.isEmpty()) {
                PrintWriter writerCPP = new PrintWriter(new FileWriter(pathCPP, true));
                writerCPP.print(textCPP);
                writerCPP.close();
            }
        } catch (Exception e) {
            System.out.println("ERROR: ");
        }

        modelManager.storePlanElement(Types.BEHAVIOUR, behaviour,true);
        this.fireEvent(ModelEventType.ELEMENT_CREATED, this.behaviour);
    }
}
