package de.unikassel.vs.alica.planDesigner.events;

public enum GuiEventType {

    CREATE_ELEMENT, DELETE_ELEMENT, ADD_ELEMENT, REMOVE_ELEMENT, REMOVE_ALL_ELEMENTS, SAVE_ELEMENT, RELOAD_ELEMENT, CHANGE_ELEMENT, MOVE_FILE, CHANGE_POSITION, GENERATE_ELEMENT, GENERATE_ALL_ELEMENTS
}
