package de.uni_kassel.vs.cn.planDesigner.alica.configuration;

import java.util.ResourceBundle;

/**
 * Created by marci on 16.10.16.
 */
public class Configuration {

    private String rolesPath;

    private String rootPath;

    private String plansPath;

    /**
     * Path to generated code
     */
    private String expressionValidatorsPath;

    private String miscPath;

    private boolean pathsInitialized;

    public Configuration() {
        try {
            ResourceBundle resourceBundle = ResourceBundle.getBundle("test");
            if (resourceBundle != null) {
                setPlansPath(String.valueOf(resourceBundle.getObject("plansPath")));
                setExpressionValidatorsPath(String.valueOf(resourceBundle.getObject("expressionValidatorsPath")));
                setMiscPath(String.valueOf(resourceBundle.getObject("miscPath")));
                setRolesPath(String.valueOf(resourceBundle.getObject("rolesPath")));
                pathsInitialized = true;
            } else {
                pathsInitialized = false;
            }
            /*
            setPlansPath(new File("/home/marci/cnws/src/cnc-msl/etc/plans").toPath());
            setExpressionValidatorsPath(new File("/home/marci/cnws/src/cnc-msl/msl_expressions/autogenerated").toPath());
            setMiscPath(new File("/home/marci/cnws/src/cnc-msl/etc/Misc").toPath());
            setRolesPath(new File("/home/marci/cnws/src/cnc-msl/etc/roles").toPath());*/

        } catch (RuntimeException e) {
            e.printStackTrace();
        }
    }

    public String getRolesPath() {
        return rolesPath;
    }

    public void setRolesPath(String rolesPath) {
        this.rolesPath = rolesPath;
    }

    public String getRootPath() {
        return rootPath;
    }

    public void setRootPath(String rootPath) {
        this.rootPath = rootPath;
    }

    public String getPlansPath() {
        return plansPath;
    }

    public void setPlansPath(String plansPath) {
        this.plansPath = plansPath;
    }

    public String getExpressionValidatorsPath() {
        return expressionValidatorsPath;
    }

    public void setExpressionValidatorsPath(String expressionValidatorsPath) {
        this.expressionValidatorsPath = expressionValidatorsPath;
    }

    public String getMiscPath() {
        return miscPath;
    }

    public void setMiscPath(String miscPath) {
        this.miscPath = miscPath;
    }

    public boolean isPathsInitialized() {
        return pathsInitialized;
    }
}
