package de.uni_kassel.vs.cn.planDesigner.alica.configuration;

import java.io.File;
import java.util.ResourceBundle;

/**
 * Created by marci on 16.10.16.
 */
public class Configuration {

    private String rolesPath;

    private String plansPath;

    /**
     * Path to generated code
     */
    private String expressionValidatorsPath;

    private String miscPath;

    private String pluginPath;

    private String defaultPluginName;

    private boolean pathsInitialized;

    public Configuration() {
        try {
            ResourceBundle resourceBundle = ResourceBundle.getBundle("test");
            if (resourceBundle != null) {
                setPlansPath(resourceBundle.getString("plansPath"));
                setExpressionValidatorsPath(resourceBundle.getString("expressionValidatorsPath"));
                setMiscPath(resourceBundle.getString("miscPath"));
                setRolesPath(resourceBundle.getString("rolesPath"));
                setPluginPath(resourceBundle.getString("pluginPath"));
                pathsInitialized = true;
            } else {
                pathsInitialized = false;
            }
            /*
            setPlansPath(new File("/home/marci/cnws/src/cnc-msl/etc/plans").toPath());
            setExpressionValidatorsPath(new File("/home/marci/cnws/src/cnc-msl/msl_expressions/autogenerated").toPath());
            setMiscPath(new File("/home/marci/cnws/src/cnc-msl/etc/Misc").toPath());
            setRolesPath(new File("/home/marci/cnws/src/cnc-msl/etc/roles").toPath());*/

        } catch (RuntimeException e) {
            e.printStackTrace();
        }
    }

    private String replaceBashConstants(String pathWithConstants) {
        try {
            String bashConstant = pathWithConstants
                    .substring(pathWithConstants.indexOf("$"), pathWithConstants.indexOf(File.separator));
            String bashConstantValue = System.getenv().get(bashConstant.substring(1));
            return pathWithConstants.replace(bashConstant, bashConstantValue);
        } catch (Exception e) {
            return pathWithConstants;
        }
    }

    public String getRolesPath() {
        return rolesPath;
    }

    public void setRolesPath(String rolesPath) {
        this.rolesPath = replaceBashConstants(rolesPath);
    }

    public String getPlansPath() {
        return plansPath;
    }

    public void setPlansPath(String plansPath) {
        this.plansPath = replaceBashConstants(plansPath);
    }

    public String getExpressionValidatorsPath() {
        return expressionValidatorsPath;
    }

    public void setExpressionValidatorsPath(String expressionValidatorsPath) {
        this.expressionValidatorsPath = replaceBashConstants(expressionValidatorsPath);
    }

    public String getMiscPath() {
        return miscPath;
    }

    public void setMiscPath(String miscPath) {
        this.miscPath = replaceBashConstants(miscPath);
    }

    public boolean isPathsInitialized() {
        return pathsInitialized;
    }

    public String getPluginPath() {
        return pluginPath;
    }

    public void setPluginPath(String pluginPath) {
        this.pluginPath = replaceBashConstants(pluginPath);
    }

    public String getDefaultPlugin() {
        return defaultPluginName;
    }

    public void setDefaultPlugin(String pluginName) {
        defaultPluginName = pluginName;
    }
}
